### PR TITLE
Fixed spelling mistake.

### PR DESCRIPTION
**Pull request by cdevroe**
Simple PR, but also greasing the wheels for future ones.

### CODE REVIEW

**Comment by dshanske** [comment]
Wrong file for changing the string, but thanks for the fix, I will commit it. The pot file is autogenerated. The line is in class-bridgy-config

**Comment by cdevroe** [comment]
@dshanske :( I'm zero help.

**Comment by dshanske** [comment]
Not true

**Comment by cdevroe** [comment]
@dshanske There, fixed it. Sorry about that.

Should compiled files (the POT) be in the repo?

**Comment by dshanske** [comment]
Fixed this.

**Pull request closed without merging**
